### ISSUE TITLE
Static methods without modifiers

### ISSUE THREAD

**Issue by lmcarreiro** [maylukas/openui5-typescript-definition-parser#1]
I've noticed that there is no method with `static` modifier, even when the method is static.

I take a look at the code and saw that it is commented:

```typescript
let matchingExceptions = MethodParser._exceptions.filter((e) => e.methodName === this.method.name && e.applicableReturnTypes.indexOf(returnValue) > -1 && e.applicableSignatures.indexOf(ParamParser.parseParams(this.method.parameters)) > -1)
let accessModifier = "";
/*if (this.method.static) {
    accessModifier += " static";
}*/

if (this.method.name === "getControlMessages") {
    console.log();
}
```

Why?

**Comment by maylukas** [comment]
Hello @lmcarreiro. That is true! The reason I commented is, that when I was parsing the declarations, a lot of methods were wrongly declared as static which made it impossible to work with the typescript definitions.
I will need to revalidate if this is still the case.

**Comment by lmcarreiro** [comment]
It makes sense, there are a lot of wrong things in the API. I've worked on a generator of these definitions too, to use with my npm package (https://www.npmjs.com/package/ui5ts), and now I think that there are a little less errors.
